import { createElement } from "react";
import {
  Apple,
  Armchair,
  Baby,
  Bath,
  Bed,
  BedDouble,
  Bike,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  CalendarDays,
  Camera,
  Car,
  Caravan,
  Cat,
  ChefHat,
  Clock,
  Coffee,
  Construction,
  CookingPot,
  Cpu,
  Dices,
  Dog,
  Drill,
  Drone,
  Dumbbell,
  Ellipsis,
  Factory,
  Fish,
  Flower2,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  GraduationCap,
  Guitar,
  Hammer,
  HardHat,
  Headphones,
  Heart,
  Hospital,
  Hotel,
  House,
  Key,
  Keyboard,
  Lamp,
  LampDesk,
  LandPlot,
  Laptop,
  Library,
  Microwave,
  Monitor,
  Motorbike,
  Mouse,
  Music,
  Package,
  Paintbrush,
  Palette,
  PawPrint,
  Pill,
  Plane,
  Printer,
  Puzzle,
  Refrigerator,
  Router,
  Sailboat,
  School,
  Scissors,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  Smartphone,
  Sofa,
  Speaker,
  Sprout,
  Stethoscope,
  Store,
  Tablet,
  Tag,
  Tent,
  Tractor,
  Trees,
  Trophy,
  Truck,
  Tv,
  UserRound,
  Users,
  Utensils,
  Volleyball,
  Warehouse,
  WashingMachine,
  Watch,
  Wheat,
  Wrench,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

/*
 * Cột categories.icon lưu tên icon lucide-react dạng kebab-case ("briefcase-business").
 * Chỉ import các icon trong bảng dưới (không import cả bộ lucide để bundle nhỏ);
 * đây cũng là bộ icon Admin chọn được ở trang /admin/danh-muc. Tên lạ hiển thị icon mặc định Package.
 */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  apple: Apple,
  armchair: Armchair,
  baby: Baby,
  bath: Bath,
  bed: Bed,
  "bed-double": BedDouble,
  bike: Bike,
  "book-open": BookOpen,
  briefcase: Briefcase,
  "briefcase-business": BriefcaseBusiness,
  building: Building,
  "building-2": Building2,
  bus: Bus,
  "calendar-days": CalendarDays,
  camera: Camera,
  car: Car,
  caravan: Caravan,
  cat: Cat,
  "chef-hat": ChefHat,
  clock: Clock,
  coffee: Coffee,
  construction: Construction,
  "cooking-pot": CookingPot,
  cpu: Cpu,
  dices: Dices,
  dog: Dog,
  drill: Drill,
  drone: Drone,
  dumbbell: Dumbbell,
  ellipsis: Ellipsis,
  factory: Factory,
  fish: Fish,
  "flower-2": Flower2,
  footprints: Footprints,
  fuel: Fuel,
  "gamepad-2": Gamepad2,
  gem: Gem,
  gift: Gift,
  glasses: Glasses,
  "graduation-cap": GraduationCap,
  guitar: Guitar,
  hammer: Hammer,
  "hard-hat": HardHat,
  headphones: Headphones,
  heart: Heart,
  hospital: Hospital,
  hotel: Hotel,
  house: House,
  key: Key,
  keyboard: Keyboard,
  lamp: Lamp,
  "lamp-desk": LampDesk,
  "land-plot": LandPlot,
  laptop: Laptop,
  library: Library,
  microwave: Microwave,
  monitor: Monitor,
  motorbike: Motorbike,
  mouse: Mouse,
  music: Music,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  "paw-print": PawPrint,
  pill: Pill,
  plane: Plane,
  printer: Printer,
  puzzle: Puzzle,
  refrigerator: Refrigerator,
  router: Router,
  sailboat: Sailboat,
  school: School,
  scissors: Scissors,
  ship: Ship,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  shovel: Shovel,
  smartphone: Smartphone,
  sofa: Sofa,
  speaker: Speaker,
  sprout: Sprout,
  stethoscope: Stethoscope,
  store: Store,
  tablet: Tablet,
  tag: Tag,
  tent: Tent,
  tractor: Tractor,
  trees: Trees,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  "user-round": UserRound,
  users: Users,
  utensils: Utensils,
  volleyball: Volleyball,
  warehouse: Warehouse,
  "washing-machine": WashingMachine,
  watch: Watch,
  wheat: Wheat,
  wrench: Wrench,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

export function getCategoryIcon(name: string | null | undefined): LucideIcon {
  return (name && CATEGORY_ICONS[name]) || Package;
}

/** Icon của danh mục theo tên lưu trong DB. */
export function CategoryIcon({ name, ...props }: LucideProps & { name: string | null | undefined }) {
  return createElement(getCategoryIcon(name), props);
}
